[phases.setup]
nixPkgs = ["chromium", "nodejs_18"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node src/index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"
